### ISSUE TITLE
bash scripts/train_xx.sh，训练时报错，是怎么回事呢

### ISSUE THREAD

**Issue by lxh0319** [Fictionarry/TalkingGaussian#24]
Loading model from: /root/xxx/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth [06/08 07:17:43]
Training progress:   0%|                                                                                                                                                    | 0/50000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_face.py", line 394, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_face.py", line 147, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/xxx/TalkingGaussian/gaussian_renderer/__init__.py", line 94, in render
    cov3D_precomp = cov3D_precomp)
ValueError: not enough values to unpack (expected 4, got 3)

Exception ignored in: <function tqdm.__del__ at 0x7fd43548f710>
Traceback (most recent call last):
  File "/xxx/lib/python3.7/site-packages/tqdm/std.py", line 1145, in __del__
  File "/xxx/lib/python3.7/site-packages/tqdm/std.py", line 1299, in close
  File "/xxx/lib/python3.7/site-packages/tqdm/std.py", line 1492, in display
  File "/xxx/lib/python3.7/site-packages/tqdm/std.py", line 1148, in __str__
  File "/xxx/lib/python3.7/site-packages/tqdm/std.py", line 1450, in format_dict
  File "/xxx/lib/python3.7/site-packages/tqdm/utils.py", line 267, in _screen_shape_linux
TypeError: 'NoneType' object is not callable

**Comment by Fictionarry** [comment]
看起来是rasterizer的问题，不知道你用的是不是原版3dgs的gaussian rasterizer，本项目里用的跟原版不太一样，需要重新下载安装一下

**Comment by lxh0319** [comment]
好的，谢谢了

**Comment by lxh0319** [comment]
> 看起来是rasterizer的问题，不知道你用的是不是原版3dgs的gaussian rasterizer，本项目里用的跟原版不太一样，需要重新下载安装一下

好的，谢谢了
