### ISSUE TITLE
请问嘴型对齐的效果还能提升吗？

### ISSUE THREAD

**Issue by charryshi** [Fictionarry/TalkingGaussian#32]
感谢您的开源贡献
测试了一下，使用DeepSpeech做的Audio Pre-process，语言是英语。生成的视频感觉唇形对齐这块感觉有点不太一致。过程中有一些error但好像生成流程没问题，麻烦请问一下这块是我还有什么问题没解决引发吗，还能提升吗。

https://github.com/user-attachments/assets/b8c25741-27e9-4906-aaae-b5bda163a3e0

$bash scripts/train_xx.sh data/1 output/test/ 0
Traceback (most recent call last):
  File "/home/user/TalkingGaussian/train_mouth.py", line 28, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 10, in <module>
    from tensorboard.compat.proto import event_pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/user/TalkingGaussian/train_face.py", line 28, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 10, in <module>
    from tensorboard.compat.proto import event_pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/user/TalkingGaussian/train_fuse.py", line 28, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 10, in <module>
    from tensorboard.compat.proto import event_pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Looking for config file in output/test/cfg_args
Config file found: output/test/cfg_args
Rendering output/test/
Found transforms_train.json file, assuming Blender data set! [22/08 14:07:18]
Reading Test Transforms [22/08 14:07:18]
794it [00:00, 9100.44it/s]
794it [00:19, 40.06it/s]
Generating random point cloud (10000)... [22/08 14:07:39]
Loading Training Cameras [22/08 14:07:39]
Loading Test Cameras [22/08 14:07:40]
Number of points at initialisation :  10000 [22/08 14:07:40]
Rendering progress: 100%|########################| 794/794 [00:08<00:00, 88.81it/s]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/user/miniconda3/envs/talking_gaussian/lib/python3.9/site-packages/lpips/weights/v0.1/alex.pth
100
200
300
400
500
600
700
LMD (fan) = 2.369922
PSNR = 35.660026
LPIPS (alex) = 0.018883

$ python synthesize_fuse.py -S data/1  -M output/test/ --use_train --audio data/1/whatdidiknow.npy
Looking for config file in output/test/cfg_args
Config file found: output/test/cfg_args
Rendering output/test/
Found transforms_train.json file, assuming Blender data set! [22/08 14:11:14]
Reading Training Transforms [22/08 14:11:14]
7938it [00:00, 8977.61it/s]
165it [00:04, 38.08it/s]
Reading Test Transforms [22/08 14:11:20]
794it [00:00, 8989.86it/s]
165it [00:04, 38.33it/s]
Generating random point cloud (10000)... [22/08 14:11:24]
Loading Training Cameras [22/08 14:11:25]
Loading Test Cameras [22/08 14:11:25]
Number of points at initialisation :  10000 [22/08 14:11:25]
Rendering progress: 100%|########################| 165/165 [00:02<00:00, 67.60it/s]

**Comment by Fictionarry** [comment]
您这个应该是没训练完，只训练了10k步就报错停了，先把protobuf降到3.19.0之后训完50k步看看效果吧

**Comment by charryshi** [comment]
谢谢您的回复，应该是这个问题。
我是在CUDA 12下，一点点调整了一下各个包安装的。
我调整了一下protobuf版本，没报错了，但日志到
Optimizing output/test
Output folder: output/test [24/08 21:56:28]
Found transforms_train.json file, assuming Blender data set! [24/08 21:56:28]
Reading Training Transforms [24/08 21:56:28]
7938it [00:00, 8982.10it/s]
7938it [03:15, 40.69it/s]
Reading Test Transforms [24/08 21:59:45]
794it [00:00, 8916.05it/s]
794it [00:19, 40.55it/s]
Generating random point cloud (10000)... [24/08 22:00:05]
Loading Training Cameras [24/08 22:00:05]
Loading Test Cameras [24/08 22:00:12]
Number of points at initialisation :  10000 [24/08 22:00:13]
就卡住了，cpu和gpu都没动静，看了一下应该是代码这儿卡住在这儿了
https://github.com/Fictionarry/TalkingGaussian/blob/5acdaaa4508ccbeefc29673abc540430fe077c1e/train_mouth.py#L51

没出现报错，进程也没退出，看起来也没资源开销或阻塞，不知道啥问题了

**Comment by charryshi** [comment]
一点点调试找到问题搞定了
~/TalkingGaussian/gridencoder$ pip install -e .
重新安装组件后可以正常train了。之前日志没有任何报错有点怪，调试才怀疑到这个组件有问题。
完成后比之前效果要好一些了。继续研究
感谢！
