### ISSUE TITLE
ZeroDivisionError during training

### ISSUE THREAD

**Issue by MahlerMozart** [Fictionarry/TalkingGaussian#41]
ptimizing output/may_cut
Output folder: output/may_cut [15/09 18:06:45]
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
scripts/train_xx.sh: line 8:  7139 Aborted                 (core dumped) python train_mouth.py -s $dataset -m $workspace --audio_extractor $audio_extractor
Optimizing output/may_cut
Output folder: output/may_cut [15/09 18:06:46]
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
scripts/train_xx.sh: line 9:  7167 Aborted                 (core dumped) python train_face.py -s $dataset -m $workspace --init_num 2000 --densify_grad_threshold 0.0005 --audio_extractor $audio_extractor
Optimizing output/may_cut
Output folder: output/may_cut [15/09 18:06:47]
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
scripts/train_xx.sh: line 10:  7194 Aborted                 (core dumped) python train_fuse.py -s $dataset -m $workspace --opacity_lr 0.001 --audio_extractor $audio_extractor
Looking for config file in output/may_cut/cfg_args
Config file found: output/may_cut/cfg_args
Rendering output/may_cut
Found transforms_train.json file, assuming Blender data set! [15/09 18:06:48]
Reading Test Transforms [15/09 18:06:48]
137it [00:00, 4946.11it/s]
137it [00:01, 72.23it/s]
Generating random point cloud (10000)... [15/09 18:06:50]
Loading Training Cameras [15/09 18:06:50]
Loading Test Cameras [15/09 18:06:51]
Number of points at initialisation :  10000 [15/09 18:06:51]
Traceback (most recent call last):
  File "synthesize_fuse.py", line 125, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.use_train, args.fast, args.dilate)
  File "synthesize_fuse.py", line 93, in render_sets
    (model_params, motion_params, model_mouth_params, motion_mouth_params) = torch.load(os.path.join(dataset.model_path, "chkpnt_fuse_latest.pth"))
  File "/home/xxx/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/xxx/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/xxx/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/may_cut/chkpnt_fuse_latest.pth'
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/xxx/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/xxx/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/xxx/miniconda3/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "metrics.py", line 215, in <module>
    print(lmd_meter.report())
  File "metrics.py", line 102, in report
    return f'LMD ({self.backend}) = {self.measure():.6f}' 
  File "metrics.py", line 96, in measure
    return self.V / self.N
ZeroDivisionError: division by zero

Someone reported this issue before and the author suggested memory size may be the issue. I cut the May video into 1 minute. During the training, I still face the ZeroDivisionError. My memory is 32Gb. Any suggestion? Thank you so much.

**Comment by Fictionarry** [comment]
The problem is actually at here
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.0). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
```
Maybe you have to adjust the version of protobuf first, so that to enable the training successfully.

**Comment by toreal** [comment]
The problem maybe at "RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 8 for tensor number 1 in the list."  
But I don't know how to solve it. Do you have any suggestions?


bash scripts/train_xx.sh data/girl  output/girl 0
Optimizing output/girl
Output folder: output/girl [01/11 02:20:11]
Found transforms_train.json file, assuming Blender data set! [01/11 02:20:12]
Reading Training Transforms [01/11 02:20:12]
3153it [00:01, 1927.01it/s]
3153it [01:34, 33.25it/s]
Reading Test Transforms [01/11 02:21:49]
316it [00:00, 1923.58it/s]
312it [00:09, 33.69it/s][warnining] audio feature is too short [01/11 02:21:59]
312it [00:09, 33.46it/s]
Generating random point cloud (10000)... [01/11 02:21:59]
Loading Training Cameras [01/11 02:21:59]
Loading Test Cameras [01/11 02:22:04]
Number of points at initialisation :  10000 [01/11 02:22:04]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] [01/11 02:22:05]
/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth [01/11 02:22:05]
Training progress:   4%|4          | 2000/50000 [00:12<04:31, 176.67it/s, Loss=0.00179, AU25=1.5-1.6]
[ITER 2000] Evaluating test: L1 0.26607178449630736 PSNR 6.733436107635498 [01/11 02:22:19]

[ITER 2000] Evaluating train: L1 0.26527885198593143 PSNR 6.75002088546753 [01/11 02:22:20]
Training progress:   4%|4          | 2200/50000 [00:15<05:24, 147.31it/s, Loss=0.00208, AU25=1.5-1.6]Traceback (most recent call last):
  File "train_mouth.py", line 328, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_mouth.py", line 215, in training
    shs_view = gaussians.get_features.transpose(1, 2).view(-1, 3, (gaussians.max_sh_degree+1)**2)
  File "/home/user/TalkingGaussian/scene/gaussian_model.py", line 116, in get_features
    return torch.cat((features_dc, features_rest), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 8 for tensor number 1 in the list.
Exception ignored in: <function tqdm.__del__ at 0x7f35f3577b90>
Traceback (most recent call last):
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1145, in __del__
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1299, in close
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1492, in display
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1148, in __str__
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/std.py", line 1450, in format_dict
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/tqdm/utils.py", line 267, in _screen_shape_linux
TypeError: 'NoneType' object is not callable
Optimizing output/girl
Output folder: output/girl [01/11 02:22:24]
Found transforms_train.json file, assuming Blender data set! [01/11 02:22:25]
Reading Training Transforms [01/11 02:22:25]
3153it [00:01, 1914.81it/s]
3153it [01:34, 33.23it/s]
Reading Test Transforms [01/11 02:24:02]
316it [00:00, 1906.08it/s]
312it [00:09, 33.65it/s][warnining] audio feature is too short [01/11 02:24:12]
312it [00:09, 33.51it/s]
Generating random point cloud (2000)... [01/11 02:24:12]
Loading Training Cameras [01/11 02:24:12]
Loading Test Cameras [01/11 02:24:17]
Number of points at initialisation :  2000 [01/11 02:24:17]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] [01/11 02:24:17]
/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth [01/11 02:24:18]
Training progress:   4%|4         | 2000/50000 [00:11<04:53, 163.38it/s, Loss=0.05900, Mouth=1.6-8.0]
[ITER 2000] Evaluating test: L1 0.03520116308017781 PSNR 20.023672906975996 [01/11 02:24:32]

[ITER 2000] Evaluating train: L1 0.030914516001939774 PSNR 21.484372329711917 [01/11 02:24:34]
Training progress:   8%|8          | 4000/50000 [00:42<14:01, 54.68it/s, Loss=0.01016, Mouth=2.4-8.8]
[ITER 4000] Evaluating test: L1 0.03265880881563613 PSNR 19.04346425909745 [01/11 02:25:03]

[ITER 4000] Evaluating train: L1 0.032561696320772174 PSNR 18.908275985717776 [01/11 02:25:06]
Training progress:  12%|#3         | 6000/50000 [01:24<13:17, 55.20it/s, Loss=0.01587, Mouth=3.2-9.6]
[ITER 6000] Evaluating test: L1 0.03324528636508866 PSNR 18.832395754362405 [01/11 02:25:45]

[ITER 6000] Evaluating train: L1 0.03408423215150833 PSNR 18.4128719329834 [01/11 02:25:48]
Training progress:  16%|#6        | 8000/50000 [02:06<12:39, 55.27it/s, Loss=0.00524, Mouth=4.0-10.4]
[ITER 8000] Evaluating test: L1 0.03292598683190973 PSNR 18.861123837922747 [01/11 02:26:27]

[ITER 8000] Evaluating train: L1 0.034265464171767235 PSNR 18.355935668945314 [01/11 02:26:29]
Training progress:  20%|#8       | 10000/50000 [02:47<12:11, 54.69it/s, Loss=0.00699, Mouth=4.8-11.2]
[ITER 10000] Evaluating test: L1 0.032951714372948596 PSNR 18.901548887553968 [01/11 02:27:08]

[ITER 10000] Evaluating train: L1 0.034051183983683585 PSNR 18.44828567504883 [01/11 02:27:11]

[ITER 10000] Saving Gaussians [01/11 02:27:11]

[ITER 10000] Saving Checkpoint [01/11 02:27:11]
Training progress:  24%|##1      | 12000/50000 [03:29<11:31, 54.92it/s, Loss=0.01257, Mouth=5.6-12.0]
[ITER 12000] Evaluating test: L1 0.0327150164858291 PSNR 18.938732950310957 [01/11 02:27:50]

[ITER 12000] Evaluating train: L1 0.033628519624471664 PSNR 18.511128234863282 [01/11 02:27:53]
Training progress:  28%|##5      | 14000/50000 [04:11<10:53, 55.07it/s, Loss=0.02678, Mouth=6.4-12.8]
[ITER 14000] Evaluating test: L1 0.03270698181892696 PSNR 18.97332271776701 [01/11 02:28:32]

[ITER 14000] Evaluating train: L1 0.03344566896557808 PSNR 18.616846466064455 [01/11 02:28:34]
Training progress:  32%|##8      | 16000/50000 [04:53<10:17, 55.04it/s, Loss=0.00578, Mouth=7.2-13.6]
[ITER 16000] Evaluating test: L1 0.03243510611355305 PSNR 19.036945543791116 [01/11 02:29:14]

[ITER 16000] Evaluating train: L1 0.03363056853413582 PSNR 18.59799690246582 [01/11 02:29:16]
Training progress:  36%|###2     | 18000/50000 [05:34<09:42, 54.91it/s, Loss=0.01212, Mouth=8.0-14.4]
[ITER 18000] Evaluating test: L1 0.03232250460668614 PSNR 19.07985406172903 [01/11 02:29:56]

[ITER 18000] Evaluating train: L1 0.03328476175665856 PSNR 18.66069221496582 [01/11 02:29:58]
Training progress:  40%|###6     | 20000/50000 [06:16<09:05, 54.95it/s, Loss=0.01884, Mouth=8.8-15.2]
[ITER 20000] Evaluating test: L1 0.03223902055699574 PSNR 19.088668421695107 [01/11 02:30:38]

[ITER 20000] Evaluating train: L1 0.03308735378086567 PSNR 18.7146484375 [01/11 02:30:40]

[ITER 20000] Saving Gaussians [01/11 02:30:40]

[ITER 20000] Saving Checkpoint [01/11 02:30:40]
Training progress:  44%|###9     | 22000/50000 [06:58<08:28, 55.03it/s, Loss=0.00512, Mouth=9.6-16.0]
[ITER 22000] Evaluating test: L1 0.03253571502864361 PSNR 19.088850824456465 [01/11 02:31:20]

[ITER 22000] Evaluating train: L1 0.033412421122193336 PSNR 18.71449546813965 [01/11 02:31:22]
Training progress:  48%|###8    | 24000/50000 [07:40<07:55, 54.72it/s, Loss=0.00819, Mouth=10.4-16.8]
[ITER 24000] Evaluating test: L1 0.03230110006897073 PSNR 19.110510575143913 [01/11 02:32:01]

[ITER 24000] Evaluating train: L1 0.033169005438685416 PSNR 18.720870590209962 [01/11 02:32:04]
Training progress:  52%|####1   | 26000/50000 [08:22<07:15, 55.06it/s, Loss=0.01218, Mouth=11.2-17.6]
[ITER 26000] Evaluating test: L1 0.03232521112812193 PSNR 19.11694586904425 [01/11 02:32:43]

[ITER 26000] Evaluating train: L1 0.03327131196856499 PSNR 18.703716278076172 [01/11 02:32:46]
Training progress:  56%|####4   | 28000/50000 [09:04<06:40, 54.90it/s, Loss=0.02509, Mouth=12.0-18.4]
[ITER 28000] Evaluating test: L1 0.03240744769573212 PSNR 19.135572533858447 [01/11 02:33:25]

[ITER 28000] Evaluating train: L1 0.033213584497570996 PSNR 18.74058723449707 [01/11 02:33:28]
Training progress:  60%|####8   | 30000/50000 [09:46<06:05, 54.67it/s, Loss=0.00621, Mouth=12.8-19.2]
[ITER 30000] Evaluating test: L1 0.032018724730924555 PSNR 19.161974957114772 [01/11 02:34:07]

[ITER 30000] Evaluating train: L1 0.03314627334475517 PSNR 18.737094497680665 [01/11 02:34:09]

[ITER 30000] Saving Gaussians [01/11 02:34:09]

[ITER 30000] Saving Checkpoint [01/11 02:34:10]
Training progress:  64%|#####1  | 32000/50000 [10:28<05:28, 54.72it/s, Loss=0.00885, Mouth=13.6-20.0]
[ITER 32000] Evaluating test: L1 0.03221268226441584 PSNR 19.107181649459033 [01/11 02:34:49]

[ITER 32000] Evaluating train: L1 0.033325108140707015 PSNR 18.667801666259766 [01/11 02:34:52]
Training progress:  68%|#####4  | 34000/50000 [11:10<04:54, 54.35it/s, Loss=0.01504, Mouth=14.4-20.8]
[ITER 34000] Evaluating test: L1 0.032147856429219246 PSNR 19.177336140682822 [01/11 02:35:31]

[ITER 34000] Evaluating train: L1 0.0330487035214901 PSNR 18.781600952148438 [01/11 02:35:34]
Training progress:  72%|#####7  | 36000/50000 [11:53<04:21, 53.58it/s, Loss=0.00596, Mouth=15.2-21.6]
[ITER 36000] Evaluating test: L1 0.032474615268017114 PSNR 19.132450204146533 [01/11 02:36:14]

[ITER 36000] Evaluating train: L1 0.03348513059318066 PSNR 18.725484085083007 [01/11 02:36:16]
Training progress:  76%|######  | 38000/50000 [12:35<03:42, 53.96it/s, Loss=0.00726, Mouth=16.0-22.4]
[ITER 38000] Evaluating test: L1 0.03163300503633524 PSNR 19.243800916169818 [01/11 02:36:57]

[ITER 38000] Evaluating train: L1 0.03272325024008751 PSNR 18.83039894104004 [01/11 02:36:59]
Training progress:  80%|######4 | 40000/50000 [13:19<03:09, 52.85it/s, Loss=0.01303, Mouth=16.8-23.2]
[ITER 40000] Evaluating test: L1 0.03174297737055703 PSNR 19.24451516803942 [01/11 02:37:40]

[ITER 40000] Evaluating train: L1 0.03270529806613922 PSNR 18.863579940795898 [01/11 02:37:42]

[ITER 40000] Saving Gaussians [01/11 02:37:42]

[ITER 40000] Saving Checkpoint [01/11 02:37:42]
Training progress:  84%|######7 | 42000/50000 [14:01<02:25, 54.86it/s, Loss=0.02589, Mouth=17.6-24.0]
[ITER 42000] Evaluating test: L1 0.03181898750756916 PSNR 19.21115403426321 [01/11 02:38:22]

[ITER 42000] Evaluating train: L1 0.032594759762287144 PSNR 18.860652923583984 [01/11 02:38:24]
Training progress:  88%|####### | 44000/50000 [14:43<01:49, 54.76it/s, Loss=0.00558, Mouth=18.4-24.8]
[ITER 44000] Evaluating test: L1 0.03182821054207651 PSNR 19.206525501451992 [01/11 02:39:04]

[ITER 44000] Evaluating train: L1 0.032557861506938936 PSNR 18.859840393066406 [01/11 02:39:06]
Training progress:  92%|#######3| 46000/50000 [15:25<01:13, 54.48it/s, Loss=0.03056, Mouth=19.2-25.6]
[ITER 46000] Evaluating test: L1 0.031677080710467535 PSNR 19.21025346454821 [01/11 02:39:46]

[ITER 46000] Evaluating train: L1 0.03249254301190376 PSNR 18.854668807983398 [01/11 02:39:48]
Training progress:  96%|#######6| 48000/50000 [16:21<01:05, 30.51it/s, Loss=0.05612, Mouth=20.0-26.4]
[ITER 48000] Evaluating test: L1 0.029918176072992776 PSNR 19.5938875298751 [01/11 02:40:42]

[ITER 48000] Evaluating train: L1 0.023388715833425524 PSNR 22.124017333984376 [01/11 02:40:45]
Training progress: 100%|########| 50000/50000 [17:32<00:00, 47.49it/s, Loss=0.05864, Mouth=20.8-27.2]

[ITER 50000] Evaluating test: L1 0.029450798015061175 PSNR 19.591847971866006 [01/11 02:41:53]

[ITER 50000] Evaluating train: L1 0.02219633013010025 PSNR 22.390225982666017 [01/11 02:41:56]

[ITER 50000] Saving Gaussians [01/11 02:41:56]

[ITER 50000] Saving Checkpoint [01/11 02:41:56]

Training complete. [01/11 02:41:57]
Optimizing output/girl
Output folder: output/girl [01/11 02:42:00]
Found transforms_train.json file, assuming Blender data set! [01/11 02:42:01]
Reading Training Transforms [01/11 02:42:01]
3153it [00:01, 1913.66it/s]
3153it [01:34, 33.29it/s]
Reading Test Transforms [01/11 02:43:38]
316it [00:00, 1925.32it/s]
312it [00:09, 33.76it/s][warnining] audio feature is too short [01/11 02:43:47]
312it [00:09, 33.62it/s]
Generating random point cloud (10000)... [01/11 02:43:47]
Loading Training Cameras [01/11 02:43:48]
Loading Test Cameras [01/11 02:43:53]
Number of points at initialisation :  10000 [01/11 02:43:53]
Traceback (most recent call last):
  File "train_fuse.py", line 261, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_fuse.py", line 61, in training
    (model_params, motion_params, _, _) = torch.load(os.path.join(scene.model_path, "chkpnt_mouth_latest.pth"))
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/girl/chkpnt_mouth_latest.pth'
Looking for config file in output/girl/cfg_args
Config file found: output/girl/cfg_args
Rendering output/girl
Found transforms_train.json file, assuming Blender data set! [01/11 02:43:56]
Reading Test Transforms [01/11 02:43:56]
316it [00:00, 1893.36it/s]
310it [00:09, 33.23it/s][warnining] audio feature is too short [01/11 02:44:06]
312it [00:09, 32.72it/s]
Generating random point cloud (10000)... [01/11 02:44:06]
Loading Training Cameras [01/11 02:44:06]
Loading Test Cameras [01/11 02:44:08]
Number of points at initialisation :  10000 [01/11 02:44:09]
Traceback (most recent call last):
  File "synthesize_fuse.py", line 125, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.use_train, args.fast, args.dilate)
  File "synthesize_fuse.py", line 93, in render_sets
    (model_params, motion_params, model_mouth_params, motion_mouth_params) = torch.load(os.path.join(dataset.model_path, "chkpnt_fuse_latest.pth"))
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output/girl/chkpnt_fuse_latest.pth'
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/user/.conda/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth
Traceback (most recent call last):
  File "metrics.py", line 215, in <module>
    print(lmd_meter.report())
  File "metrics.py", line 102, in report
    return f'LMD ({self.backend}) = {self.measure():.6f}' 
  File "metrics.py", line 96, in measure
    return self.V / self.N
ZeroDivisionError: division by zero
