### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by xiaomaofei** [Fictionarry/TalkingGaussian#47]
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'
why？bash scripts/train_xx.sh data/  output/ 0

**Comment by Fictionarry** [comment]
Maybe it is because of an environment installation failure. Try `pip install ./submodules/diff-gaussian-rasterization`

**Comment by xiaomaofei** [comment]
(talking_gaussian) ubuntu@ubuntu-System-Product-Name:~/Desktop/TalkingGaussian$ bash scripts/train_xx.sh data/ output/  0
Optimizing output/
Output folder: output/ [11/10 10:11:57]
2024-10-11 10:11:57.788048: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-11 10:11:57.866192: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-11 10:11:58.150281: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:
2024-10-11 10:11:58.150350: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64:
2024-10-11 10:11:58.150355: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Found transforms_train.json file, assuming Blender data set! [11/10 10:11:58]
Reading Training Transforms [11/10 10:11:58]
7938it [00:01, 4931.44it/s]
3270it [00:43, 75.53it/s][warnining] audio feature is too short [11/10 10:12:43]
3274it [00:43, 74.85it/s]
Reading Test Transforms [11/10 10:12:43]
794it [00:00, 4896.21it/s]
0it [00:00, ?it/s][warnining] audio feature is too short [11/10 10:12:44]
0it [00:00, ?it/s]
Generating random point cloud (10000)... [11/10 10:12:44]
Loading Training Cameras [11/10 10:12:44]
Loading Test Cameras [11/10 10:12:46]
Number of points at initialisation :  10000 [11/10 10:12:46]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] [11/10 10:12:46]
/home/ubuntu/anaconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/ubuntu/anaconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/ubuntu/anaconda3/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth [11/10 10:12:46]
Training progress:   4%|###9                                                                                               | 1990/50000 [00:04<01:46, 451.67it/s, Loss=0.00031, AU25=1.7-1.8]Traceback (most recent call last):
  File "train_mouth.py", line 328, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_mouth.py", line 197, in training
    training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, motion_net, render if iteration < warm_step else render_motion_mouth, (pipe, background))
  File "train_mouth.py", line 268, in training_report
    validation_configs = ({'name': 'test', 'cameras' : [scene.getTestCameras()[idx % len(scene.getTestCameras())] for idx in range(5, 100, 10)]}, 
  File "train_mouth.py", line 268, in <listcomp>
    validation_configs = ({'name': 'test', 'cameras' : [scene.getTestCameras()[idx % len(scene.getTestCameras())] for idx in range(5, 100, 10)]}, 
ZeroDivisionError: integer division or modulo by zero。way？

**Comment by hu1148509978** [comment]
> (talking_gaussian) ubuntu@ubuntu-System-Product-Name:~/Desktop/TalkingGaussian$ bash scripts/train_xx.sh data/ output/ 0 Optimizing output/ Output folder: output/ [11/10 10:11:57] 2024-10-11 10:11:57.788048: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 AVX_VNNI FMA To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. 2024-10-11 10:11:57.866192: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`. 2024-10-11 10:11:58.150281: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64: 2024-10-11 10:11:58.150350: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.7/lib64: 2024-10-11 10:11:58.150355: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly. Found transforms_train.json file, assuming Blender data set! [11/10 10:11:58] Reading Training Transforms [11/10 10:11:58] 7938it [00:01, 4931.44it/s] 3270it [00:43, 75.53it/s][warnining] audio feature is too short [11/10 10:12:43] 3274it [00:43, 74.85it/s] Reading Test Transforms [11/10 10:12:43] 794it [00:00, 4896.21it/s] 0it [00:00, ?it/s][warnining] audio feature is too short [11/10 10:12:44] 0it [00:00, ?it/s] Generating random point cloud (10000)... [11/10 10:12:44] Loading Training Cameras [11/10 10:12:44] Loading Test Cameras [11/10 10:12:46] Number of points at initialisation : 10000 [11/10 10:12:46] Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off] [11/10 10:12:46] /home/ubuntu/anaconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead. f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, " /home/ubuntu/anaconda3/envs/talking_gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights. warnings.warn(msg) Loading model from: /home/ubuntu/anaconda3/envs/talking_gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/alex.pth [11/10 10:12:46] Training progress: 4%|###9 | 1990/50000 [00:04<01:46, 451.67it/s, Loss=0.00031, AU25=1.7-1.8]Traceback (most recent call last): File "train_mouth.py", line 328, in training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from) File "train_mouth.py", line 197, in training training_report(tb_writer, iteration, Ll1, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, motion_net, render if iteration < warm_step else render_motion_mouth, (pipe, background)) File "train_mouth.py", line 268, in training_report validation_configs = ({'name': 'test', 'cameras' : [scene.getTestCameras()[idx % len(scene.getTestCameras())] for idx in range(5, 100, 10)]}, File "train_mouth.py", line 268, in validation_configs = ({'name': 'test', 'cameras' : [scene.getTestCameras()[idx % len(scene.getTestCameras())] for idx in range(5, 100, 10)]}, ZeroDivisionError: integer division or modulo by zero。way？

I have encountered the same problem. How did you solve it? Looking forward to your reply :)
