### ISSUE TITLE
2分半钟的视频，训练时候报错

### ISSUE THREAD

**Issue by touwenameng** [Fictionarry/TalkingGaussian#63]
Traceback (most recent call last):
  File "train_mouth.py", line 328, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train_mouth.py", line 49, in training
    scene = Scene(dataset, gaussians)
  File "/root/autodl-tmp/TalkingGaussian/scene/__init__.py", line 47, in __init__
    scene_info = sceneLoadTypeCallbacks["Blender"](args.source_path, args.white_background, args.eval, args=args)
  File "/root/autodl-tmp/TalkingGaussian/scene/dataset_readers.py", line 256, in readNerfSyntheticInfo
    test_cam_infos = readCamerasFromTransforms(path, "transforms_val.json", white_background, extension, audio_file, audio_extractor)
  File "/root/autodl-tmp/TalkingGaussian/scene/dataset_readers.py", line 211, in readCamerasFromTransforms
    talking_dict['blink'] = torch.as_tensor(np.clip(au_blink[frame['img_id']], 0, 2) / 2)
IndexError: index 3612 is out of bounds for axis 0 with size 3612

2分半钟的视频，按照流程准备完数据集，跑训练的时候直接报index数组错误，从报错上看像是验证集数据越界，请问这有可能啥原因呢

**Comment by Fictionarry** [comment]
没有遇到过这个问题，不太清楚具体是什么原因造成的，可能是帧率之类的问题，可以检查一下au.csv中的项数是否与帧数一致

**Comment by touwenameng** [comment]
好的，我再测试一下

**Comment by touwenameng** [comment]
帧率是对上了，但是process的时候又报错了，增加了GPU和内存都不行

**Comment by 2ezInCode** [comment]
这一看就是帧数没对上

**Comment by I-hsin-Chen** [comment]
不好意思，借問一下五分鐘的影片 ( 7500 frames ) 大概要多少內存才夠? 有沒有什麼辦法可以省內存? 感激不盡
