### ISSUE TITLE
数据预处理错误 python3 data_utils/process.py /app/TalkingGaussian/data/May/May.mp4 --task 8

### ISSUE THREAD

**Issue by Tiandishihua** [Fictionarry/TalkingGaussian#8]
Traceback (most recent call last):
  File "/app/TalkingGaussian/data_utils/face_tracking/face_tracker.py", line 11, in <module>
    from render_3dmm import Render_3DMM
  File "/app/TalkingGaussian/data_utils/face_tracking/render_3dmm.py", line 6, in <module>
    from pytorch3d.renderer import (
  File "/usr/local/lib/python3.10/dist-packages/pytorch3d/renderer/__init__.py", line 9, in <module>
    from .blending import (
  File "/usr/local/lib/python3.10/dist-packages/pytorch3d/renderer/blending.py", line 12, in <module>
    from pytorch3d import _C
ImportError: /usr/local/lib/python3.10/dist-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

**Comment by yulj21** [comment]
是不是python版本过高了，用作者推荐的3.7.6版本试试呢
